r"""Exact e-processes for linear-Gaussian conditional independence.

Construction
------------
Write the hypothesis ``X indep Y | Z`` in regression form

.. math::

    X = Z^\top\alpha + \beta Y + \varepsilon, \qquad
    \varepsilon \sim N(0, \sigma^2),

so that under joint Gaussianity the null is the point null
:math:`H_0 : \beta = 0` with nuisance parameters :math:`(\alpha, \sigma)`.
Placing the *right-Haar* prior :math:`\pi(\alpha, \sigma) \propto \sigma^{-1}`
on the nuisance block under both hypotheses -- and the scale-matched prior
:math:`\beta \mid \sigma \sim N(0, \sigma^2 g)` on the tested coefficient --
the resulting Bayes factor is available in closed form.  Writing
:math:`S_{xx}, S_{xy}, S_{yy}` for the cross-products of the ``Z``-residualised
vectors, :math:`p = |Z| + 1`, :math:`G = g\,S_{yy}` and
:math:`\kappa = G/(1+G)`:

.. math::

    E_n \;=\; (1 + G)^{-1/2}\,
        \bigl(1 - \kappa\, \hat r_n^2 \bigr)^{-(n-p)/2},
    \qquad \hat r_n^2 = \frac{S_{xy}^2}{S_{xx} S_{yy}} .

Because the nuisance prior is right-Haar for the amenable location-scale group
:math:`x \mapsto c\,(x + Z\alpha)`, the Bayes factor is a non-negative
martingale in the filtration generated by the maximal invariants, hence an
e-process, and Ville's inequality applies at every stopping time.  (The
calibration of this claim is checked numerically in
``experiments/exp1_type1_calibration.py`` rather than merely asserted.)

Two properties are worth flagging because they drive the algorithm design:

* ``E_n`` depends on the data only through ``(S_xx, S_xy, S_yy, n)``, all of
  which are Schur complements of the running Gram matrix.  No per-hypothesis
  state is required.
* The prior scale ``g`` must be fixed in advance.  A ``g`` that adapts to the
  running sample size destroys the martingale property; SPRINT-CD therefore
  sets ``g`` from a warm-up prefix that is excluded from the e-process.
"""

from __future__ import annotations

import numpy as np

from ..stats import GaussianSuffStat, ResidualMoments
from .base import EProcessState

__all__ = [
    "safe_linear_log_e",
    "safe_linear_block_log_e",
    "coefficient_confidence_sequence",
    "SafeLinearCI",
]

_LOG_FLOOR = -700.0


def safe_linear_log_e(
    moments: ResidualMoments, g: float, *, beta_null: float = 0.0
) -> float:
    r"""Log e-value for :math:`H_0 : \beta = \beta_{\text{null}}`.

    Testing a non-zero ``beta_null`` simply replaces ``x`` by ``x - beta*y``
    throughout, which is what the confidence sequence inverts.
    """
    if g <= 0.0:
        raise ValueError("prior scale g must be positive")
    sxx, sxy, syy, dof = moments.sxx, moments.sxy, moments.syy, moments.dof
    if dof <= 0 or syy <= 0.0:
        return 0.0
    if beta_null != 0.0:
        sxx = sxx - 2.0 * beta_null * sxy + beta_null * beta_null * syy
        sxy = sxy - beta_null * syy
    if sxx <= 0.0:
        return 0.0
    G = g * syy
    kappa = G / (1.0 + G)
    r2 = float(np.clip((sxy * sxy) / (sxx * syy), 0.0, 1.0))
    # 1 - kappa*r2 is bounded below by 1 - kappa = 1/(1+G) > 0, so the log is safe.
    log_e = -0.5 * np.log1p(G) - 0.5 * dof * np.log1p(-kappa * r2)
    return float(max(log_e, _LOG_FLOOR))


def safe_linear_block_log_e(
    s_tt: float, s_wt: np.ndarray, S_ww: np.ndarray, dof: int, g: float
) -> float:
    r"""Block generalisation: test that a whole block of coefficients is zero.

    With ``q`` tested columns and prior :math:`\beta \mid \sigma \sim
    N(0, \sigma^2 g I_q)`,

    .. math::

        E_n = \bigl|I_q + g\,S_{ww}\bigr|^{-1/2}
              \Bigl(\frac{S_{tt}}{S_{tt} - S_{wt}^\top (S_{ww} + I_q/g)^{-1} S_{wt}}
              \Bigr)^{(n-p)/2}.

    Used by E-ICP, where the tested block is the set of environment dummies
    (and, optionally, their interactions with the candidate predictors).
    """
    if g <= 0.0:
        raise ValueError("prior scale g must be positive")
    q = int(np.size(s_wt))
    if dof <= 0 or q == 0 or s_tt <= 0.0:
        return 0.0
    S_ww = np.atleast_2d(np.asarray(S_ww, dtype=float))
    s_wt = np.asarray(s_wt, dtype=float).reshape(q)
    eye = np.eye(q)

    sign, logdet = np.linalg.slogdet(eye + g * S_ww)
    if sign <= 0:
        return 0.0
    A = S_ww + eye / g
    try:
        quad = float(s_wt @ np.linalg.solve(A, s_wt))
    except np.linalg.LinAlgError:
        quad = float(s_wt @ np.linalg.lstsq(A, s_wt, rcond=None)[0])
    quad = min(max(quad, 0.0), s_tt * (1.0 - 1e-12))
    log_e = -0.5 * logdet - 0.5 * dof * np.log1p(-quad / s_tt)
    return float(max(log_e, _LOG_FLOOR))


def coefficient_confidence_sequence(
    moments: ResidualMoments, g: float, alpha: float
) -> tuple[float, float]:
    r"""Anytime-valid confidence sequence for :math:`\beta`, in closed form.

    Obtained by inverting the family of e-values
    :math:`\{E_n(b)\}_b`: the set :math:`\{b : E_n(b) < 1/\alpha\}` is exactly
    the interval

    .. math::

        \hat\beta \pm \frac{1}{S_{yy}}
            \sqrt{\frac{\tau\,(S_{xx}S_{yy} - S_{xy}^2)}{1 - \tau}},
        \qquad
        \tau = \frac{1}{\kappa}
            \Bigl[ 1 - \bigl(\alpha / \sqrt{1+G}\bigr)^{2/(n-p)} \Bigr].

    The interval is non-degenerate whenever ``tau < 1``; ``tau`` decays like
    ``log(n)/n``, giving the ``sqrt(log n / n)`` width characteristic of
    confidence sequences.
    Because every :math:`E_n(b)` is an e-process, the interval covers the true
    :math:`\beta` simultaneously at *all* sample sizes with probability at
    least :math:`1-\alpha`.  This is the device SPRINT-CD uses to *accept*
    independence -- the direction in which evidence-accumulating e-processes
    cannot speak on their own.

    Returns ``(-inf, inf)`` when the data do not yet constrain ``beta``.
    """
    if not 0.0 < alpha < 1.0:
        raise ValueError("alpha must lie in (0, 1)")
    sxx, sxy, syy, dof = moments.sxx, moments.sxy, moments.syy, moments.dof
    if dof <= 0 or syy <= 0.0 or sxx <= 0.0:
        return (-np.inf, np.inf)

    G = g * syy
    kappa = G / (1.0 + G)
    # tau solves  (1 - kappa r^2)^(-dof/2) (1+G)^(-1/2) = 1/alpha  for r^2.
    log_c = (2.0 / dof) * (np.log(alpha) - 0.5 * np.log1p(G))
    tau = -np.expm1(log_c) / kappa  # == (1 - exp(log_c)) / kappa
    if tau >= 1.0 or tau <= 0.0:
        return (-np.inf, np.inf)

    beta_hat = sxy / syy
    gram_det = max(sxx * syy - sxy * sxy, 0.0)
    half_width = np.sqrt(tau * gram_det / (1.0 - tau)) / syy
    return (float(beta_hat - half_width), float(beta_hat + half_width))


class SafeLinearCI:
    """Conditional-independence oracle backed by streaming sufficient statistics.

    Wraps a :class:`~sprint_cd.stats.GaussianSuffStat` and exposes, for any
    ``(i, j, S)``, both directions of evidence: an e-value against
    independence and a confidence sequence that can certify it.

    Parameters
    ----------
    prior_scale:
        Prior standard deviation of ``beta`` in units of ``sigma`` per unit of
        ``Y``.  Sets ``g = prior_scale**2 / var(Y)`` using the *warm-up*
        variances, keeping ``g`` measurable with respect to data excluded from
        the e-process.
    warmup_var:
        Per-variable marginal variances from the warm-up prefix.  If omitted,
        ``g = prior_scale**2`` is used, which is appropriate for data already
        standardised.
    """

    def __init__(
        self,
        suffstat: GaussianSuffStat,
        *,
        prior_scale: float = 0.4,
        warmup_var: np.ndarray | None = None,
        ridge: float = 0.0,
    ) -> None:
        if prior_scale <= 0.0:
            raise ValueError("prior_scale must be positive")
        self.suffstat = suffstat
        self.prior_scale = float(prior_scale)
        self.ridge = float(ridge)
        if warmup_var is None:
            self._g = np.full(suffstat.d, prior_scale**2, dtype=float)
        else:
            v = np.asarray(warmup_var, dtype=float)
            if v.shape != (suffstat.d,):
                raise ValueError("warmup_var must have one entry per variable")
            v = np.where(np.isfinite(v) & (v > 0), v, 1.0)
            self._g = prior_scale**2 / v

    def g_for(self, j: int) -> float:
        """Prior scale used when ``X_j`` is the tested regressor."""
        return float(self._g[j])

    def moments(self, i: int, j: int, cond=()) -> ResidualMoments:
        return self.suffstat.residual_moments(i, j, cond, ridge=self.ridge)

    def log_e(self, i: int, j: int, cond=()) -> EProcessState:
        """Evidence *against* ``X_i indep X_j | X_cond``."""
        m = self.moments(i, j, cond)
        return EProcessState(
            log_e=safe_linear_log_e(m, self.g_for(j)), n=m.n, dof=m.dof
        )

    def symmetric_log_e(self, i: int, j: int, cond=()) -> EProcessState:
        """Orientation-free evidence, averaging the two regression directions.

        The regression form is asymmetric in ``(i, j)`` only through the prior
        scale; averaging the two e-values yields another e-value (a convex
        combination of e-values is an e-value) and removes the arbitrary choice
        of response variable.
        """
        a = self.log_e(i, j, cond).log_e
        b = self.log_e(j, i, cond).log_e
        m = np.maximum(a, b)
        log_e = m + np.log(0.5 * (np.exp(a - m) + np.exp(b - m)))
        mom = self.moments(i, j, cond)
        return EProcessState(log_e=float(log_e), n=mom.n, dof=mom.dof)

    def confidence_sequence(
        self, i: int, j: int, cond=(), *, alpha: float = 0.05
    ) -> tuple[float, float]:
        """Anytime-valid interval for the coefficient of ``X_j`` in ``X_i``'s model."""
        m = self.moments(i, j, cond)
        return coefficient_confidence_sequence(m, self.g_for(j), alpha)
